version: "3.8"
services:
  db:
    build: ./camelon-database
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: camelon
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 3
  camelon-back:
    build: ./camelon-server
    environment:
      MYSQL_DATABASE: camelon
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
  camelon-front:
    build: ./camelon-client
    ports:
      - "3000:3000"
    depends_on:
      - camelon-back 
    restart: on-failure
