version: "3.8"
services:
  db:
    build: ./camelon-database
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: camelon
    restart: always
  camelon-back:
    build: ./camelon-server
    environment:
      MYSQL_DATABASE: camelon
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
    ports:
      - "3001:3001"
    depends_on:
      - db
    restart: on-failure
  camelon-front:
    build: ./camelon-client
    ports:
      - "3000:3000"
    depends_on:
      - camelon-back 
    restart: on-failure
